### ISSUE TITLE
Live Captions sample doesn't work

### ISSUE THREAD

**Issue by jzhouw** [Azure-Samples/azure-media-player-samples#2]
this sample is broken. can you provide more details of what work needed to get live captions work on both AMS side and AMP side? Thanks

https://amp.azure.net/libs/amp/latest/samples/dynamic_live_captions.html

**Comment by IngridAtMicrosoft** [comment]
> this sample is broken. can you provide more details of what work needed to get live captions work on both AMS side and AMP side? Thanks
> 
> https://amp.azure.net/libs/amp/latest/samples/dynamic_live_captions.html

Thank you! The issue is being reviewed.  Have you read https://docs.microsoft.com/en-us/azure/media-services/latest/live-transcription

**Comment by IngridAtMicrosoft** [comment]
@jzhouw Thanks for catching this! It has been fixed.  Once the video starts playing, turn the Live CC on then scrub back to the beginning of the video.

**Comment by IngridAtMicrosoft** [comment]
#please-close
